### ISSUE TITLE
ERROR: Failed to download conservations

### ISSUE THREAD

**Issue by fancaoErik** [hkotb/xprotcas#1]
Hi!
I am trying to use the local version of xProtCAS. I tried my own pdb file without specifying a conservation file. I hoped it could automatically download one. But I got an error. Please see below. 

ERROR: Failed to download conservations, URL http://slim.icr.ac.uk/restapi/rest/get/evolution?task=get_conservation_scores_by_pdb&orthdb_taxon_id=metazoa&conservation_score_type=WCS&pdb_id=PDB, try to download it manually and pass it using the option --conservations_file.

I would appreciate it if you could help me solve this problem! 

Fan

**Comment by hkotb** [comment]
Hi Fan,

If you have provided a local PDB file to the tool, you'll also need to supply a corresponding conservation file. Alternatively, you can provide the tool with a PDB ID, and it will automatically retrieve both the conservation data and the PDB file based on the ID.

Best regards,
Hazem

**Comment by fancaoErik** [comment]
Thanks a lot, Hazem. 
I am trying to use my AlphaFold predictions as inputs so there are no PDB IDs. Is there any easy way to generate a conservation file? I looked through the article. It seems that generating a conservation file is not quite straightforward, at least for me. :)

Best
Fan

**Comment by hkotb** [comment]
Hi Fan,

At the moment, the internal pipeline we use for calculating conservation doesn't allow custom sequences to be provided. We always run our conservation through UniProt mapping first, so it will only work for proteins in UniProt. So, if your sequence is part of a UniProt or PDB sequence, you can get the conservation for that whole sequence using our services and then tailor the conservation file for your custom sequence.

The URL to get conservations for a PDB sequence, e.g. 1YCR (change the pdb_id for other pdbs):
http://slim.icr.ac.uk/restapi/rest/get/evolution?task=get_conservation_scores_by_pdb&orthdb_taxon_id=metazoa&conservation_score_type=WCS&pdb_id=1YCR

And the URL to get conservations for a Uniprot protein, e.g. Q00987 (change the accession for other proteins):
http://slim.icr.ac.uk/restapi/rest/get/evolution?task=get_conservation_score&orthdb_taxon_id=metazoa&conservation_score_type=WCS&accession=Q00987

Best regards,
Hazem

**Comment by fancaoErik** [comment]
Thanks, Hazem. It is very helpful! 

Best
Fan
